### ISSUE TITLE
Not working for CHROMECAST after android 12 update.

### ISSUE THREAD

**Issue by deepujaglan** [virresh/matvt#57] opened 2022-10-28 16:17 UTC
Hi , 
Many thanks for your efforts. But alas after Chromecast with Google tv got android 12 update. The mouse toggle is no longer working. Any further discussions with me  @ 9802535949 WhatsApp / j4jaglan@gmail.com

**Comment by virresh** [comment] 2022-11-05 05:58
Duplicate of https://github.com/virresh/matvt/issues/55
Would advise you to follow that thread instead. I'll not be able to chase individual people for feedback/discussion.

**Closed by virresh** 2022-11-05 05:58 UTC
