### ISSUE TITLE
Please reduce the sdk API level to 22

### ISSUE THREAD

**Issue by akshaysinghsandhu** [virresh/matvt#78] opened 2023-11-03 18:15 UTC
I am using moded firestick tank with custom LineageOS running 5.1.1 if possible resuce down the API level to 22.

**Comment by virresh** [comment] 2023-11-29 16:08
Hey @akshaysinghsandhu 
Thanks for the request. This has come up before and unfortunately we need a completely different way of implementing this on Android 5.

Marking this as duplicate of https://github.com/virresh/matvt/issues/29  
Feel free to chip in on that discussion if you have any ideas.

**Closed** 2023-11-29 16:08 UTC
