### ISSUE TITLE
Can't move up or down 

### ISSUE THREAD

**Issue by Kronos256** [virresh/matvt#2] opened 2021-03-03 16:28 UTC
When the app is installed and enable I can't move up or down on my TCL TV home screen. In settings and app drawer it works just fine but not on the home screen I tried reinstalling it but nothing changes as soon as I enable it I can't move up or down only left and right works on the home screen.

**Comment by virresh** [comment] 2021-03-04 04:55
Would you be able to help with debugging the issue / provide android logs?

I don't own a TCL TV so don't know what's the exact issue.

**Comment by Kronos256** [comment] 2021-03-10 15:06
> Would you be able to help with debugging the issue / provide android logs?
> 
> I don't own a TCL TV so don't know what's the exact issue.

Sorry I wasn't home last week so I couldn't send a LogCat. 
I just tested the new release and it works but I am not sure what was the problem since I updated my TV firmware also.
So happy now that it works like it should.

**Comment by Kronos256** [comment] 2021-03-10 15:26
> Would you be able to help with debugging the issue / provide android logs?
> 
> I don't own a TCL TV so don't know what's the exact issue.

Sorry I wasn't home last week so I couldn't send a LogCat.
I just tested the new release (v1.02), I thought it fixed my issue but it didn't.

**Comment by virresh** [comment] 2021-03-12 17:35
Thanks Kronos.
Couple of questions:
1. Are you sure this is the latest release? I can see only parts of the log (i.e keypresses only). Many useful events that were logged in my mouse emulation engine are not visible here. It's possible they might've been eaten up due to system clogging, but there isn't even a single one of them....
The logs that I'm after are essentially this line of code:
https://github.com/virresh/matvt/blob/10d3a246838050426bbb948959f3081a9d8348e6/app/src/main/java/io/github/virresh/matvt/engine/impl/MouseEmulationEngine.java#L338

2. Can you confirm the package name of your tv launcher. I might make some exceptions just for that app and release it with next set of changes. Will ask you to confirm when they're ready.

**Comment by lmpina** [comment] 2021-03-30 18:07
This may have something to do with the software display size setting (which affects the size of objects on the screen). On a typical TV box, there are four display size adjustments that can generally be made in Hidden Settings. When display size is at default (2nd setting), MATVT can scroll in all four directions. When the display size is maximized to largest (4th size), MATVT can only scroll up and down. It can not scroll left and right. When display size is reduced to larger (3rd size), MATVT is able to scroll in all four directions again. I know that I've described the exact opposite of your problem, but display size, magnification and resolution are all worth checking...

**Comment by virresh** [comment] 2021-03-31 04:47
Thanks for the inputs lmpina
Ideally MATVT should be able to scroll irrespective of display size, but the description you gave makes sense a bit.
I will have to adjust the length of swipe sent when scrolling to a larger value when on a larger display screen. (Seems like the finger movement during swipe isn't sufficient for large screens). 
If the issue is really what I think it is,
(i)  On the largest screen size, scrolling left and right instead sends clicks on the underlying action button?
(ii) The left right scrolling issue is reproducible everywhere and not just on the TV Home screen?

**Comment by lmpina** [comment] 2021-04-01 14:15
For clarification purposes, two Settings apps were factory installed by a recent firmware update on the H96Max RK3318 shown in "Factors affecting pointer accuracy."

1. Larger gear icon - Settings, version 9.com.android.settings
2, Smaller gear icon - Settings, v1.0, com.android.tv.settings

The path to the Display size setting interacting with MATVT (Largest size causing no vertical scroll) is: 

Smaller gear icon → Advanced (Display size, Screen saver, Device theme) → Display → Display size

![20210331_171933](https://user-images.githubusercontent.com/80218950/113305815-6679a380-92d1-11eb-9909-f0247f93cb7a.jpg)

Changing the Display size here is like hitting Control + and Control - in a browser. It makes everything easier to read on the screen, just what's needed at a leanback distance when someone needs new glasses. 

Also, for what it's worth. Larger gear icon → Display → Resolution was set to Auto; Larger gear icon Display → Zoom was adjusted so that the red, unfilled, test rectangle (adjusting VHeight and HWidth) was perfectly fit to the screen.

This issue is no big deal, IMHO, since MATVT is NOT the only app to balk at the Largest size, and it's very easy to resolve - just back off to Larger or less.

**Comment by sportica** [comment] 2021-04-04 14:37
I had the same problem with Kronos256. And it was fixed when I changed the feedback type to 'feedbackHaptic' in the accessibility service config file. 

<img width="495" alt="feedbacktype" src="https://user-images.githubusercontent.com/7854995/113512242-b50f9200-959e-11eb-8c8c-a7128976c6eb.png">

**Comment by virresh** [comment] 2021-04-08 15:11
Thanks @sportica !

I'll update the feedback type. 
I wonder if the feedback type would clash on some other devices though, but we'll see about it when we get there. This fix should suffice in the meanwhile 😄

**Comment by CaioTheBrain** [comment] 2021-04-25 00:19
The same happens to me in a Mi Box running Android TV 9, Android TV Home version 3.1.2-366946414-f and Android TV Core Services version 3.1.1-362554353-f.

Once Mouse Toggle Service is enabled at accessibility settings, the D-pad control can't move up or down in the homescreen, only left and right.

**Comment by virresh** [comment] 2021-06-26 18:27
@CaioTheBrain @Kronos256 
Released v1.04 (https://github.com/virresh/matvt/releases/tag/v1.0.4) with the above fix

Do try and let me know if there you still same issues. Thanks @sportica once again!

**Comment by CaioTheBrain** [comment] 2021-06-26 22:52
v 1.0.4 fixed it for me.

Thank you @virresh.

**Comment by virresh** [comment] 2021-06-27 05:23
Great
I'll close this issue then. 
Feel free to comment / re-open if needed.

**Closed by virresh** 2021-06-27 05:23 UTC
Labels: bug
